### ISSUE TITLE
unable to handle unknown packet type 0

### ISSUE THREAD

**Issue by P4sca1** [wisp-gg/gamequery#1]
Querying Garry's Mod servers sometimes fails with the error `unable to handle unknown packet type 0`.

**Comment by TrixterTheTux** [comment]
Would you have a sample IP I could reproduce this with?

**Comment by P4sca1** [comment]
> Would you have a sample IP I could reproduce this with?

Sure, here you go: 84.200.229.42:27015.
Querying with gamedig works btw.

**Comment by TrixterTheTux** [comment]
Should be fixed now - thanks for reporting this :)

**Comment by P4sca1** [comment]
Can confirm this has been fixed. Thank you very much for the quick fix and this very useful library.
